info:
  Description: Akkodis try-out Prices project with Spring Boot, Maven and Java 11
server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
  application:
    name: prices
  datasource:
    platform: h2
    username: sa
    password:
    url: "jdbc:h2:mem:prices;MODE=postgresql;DB_CLOSE_DELAY=-1"
    driver-class-name: org.h2.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    user: sa
    password:
